spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newone?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/practice3
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # 변경된 테이블만 반영하는 옵션
      #ddl-auto: create ## 최초 테이블을 생성하는 옵션
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

social:
  client:
    kakao:
      rest-api-key: ba50165094c8a6717bca69e014ef797d
      secret-key: nN7IyomDVGAkJm4z5nln24jQLiJzBG7Q
      grant_type: authorization_code
      redirect-uri: http://localhost:8080/camput/login/api-login
      admin-key: 09eca5bad30d56c0c80352f2eceecfa4
      logout-redirect-uri: http://localhost:8080/camput/logout

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace



